// Code generated by "stringer -type AnimalType"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Dog-0]
	_ = x[Cat-1]
	_ = x[Bird-2]
}

const _AnimalType_name = "DogCatBird"

var _AnimalType_index = [...]uint8{0, 3, 6, 10}

func (i AnimalType) String() string {
	if i < 0 || i >= AnimalType(len(_AnimalType_index)-1) {
		return "AnimalType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AnimalType_name[_AnimalType_index[i]:_AnimalType_index[i+1]]
}
