// Code generated by "stringer -type TodoStatus"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[New-0]
	_ = x[InProgress-1]
	_ = x[Done-2]
}

const _TodoStatus_name = "NewInProgressDone"

var _TodoStatus_index = [...]uint8{0, 3, 13, 17}

func (i TodoStatus) String() string {
	if i < 0 || i >= TodoStatus(len(_TodoStatus_index)-1) {
		return "TodoStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TodoStatus_name[_TodoStatus_index[i]:_TodoStatus_index[i+1]]
}
