// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func Initialize() (*DependenciesSet, error) {
	dog := provideDog()
	mySingleton := provideMySingleton()
	animalService := NewAnimalService(dog, mySingleton)
	dependenciesSet := &DependenciesSet{
		AnimalService: animalService,
	}
	return dependenciesSet, nil
}

// wire.go:

func provideDog() *Dog {
	dog := Dog{Name: "Doggy"}
	return &dog
}

var animalSet = wire.NewSet(
	provideDog, wire.Bind(new(Animal), new(*Dog)),
)

func provideMySingleton() *MySingleton {
	return &MySingleton{Name: "Bob"}
}

var mySingletonSet = wire.NewSet(
	provideMySingleton,
)

func NewAnimalService(animal Animal, mySingleton *MySingleton) AnimalService {
	return AnimalService{
		Animal:      animal,
		MySingleton: *mySingleton,
	}
}

type DependenciesSet struct {
	AnimalService AnimalService
}
