# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: api_sample

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.5"

      - name: Build
        run: |
          cd api_sample
          go build -v ./...

      - name: fmt all
        run: |
          cd api_sample
          base_dir=$(pwd)
          for p in `find . -name go.mod | xargs dirname`; do echo $p; cd $p; go fmt; cd $base_dir; done

      - name: Test all
        run: |
          cd api_sample
          base_dir=$(pwd)
          for p in `find . -name go.mod | xargs dirname`; do echo $p; cd $p; go test; cd $base_dir; done
